server:
  port: 9001
spring:
  application:
    name: tensquare-base #指定服务名
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.147.131:3306/tensquare_base?characterEncoding=utf-8
    password: 123456
    username: root
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true